[package]
name = "split_gui"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.10"
gaitool-rs = { path = "../" }
