---
name: "split gui build"

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
            comp_er: tar
            comp_args: -zcvf
            comp_type: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
            comp_er: 7z
            comp_args: 'a -tzip'
            comp_type: zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: set package name
        id: set_name
        run: echo "pkg_name=split_gui" >> $GITHUB_ENV
      - name: echo
        run: |
          echo ${{ env.pkg_name }}
      - name: install rustlang
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: build project
        run: |
          cargo build --release -p split_gui
      - name: Compress things up
        run: |
          cp ./target/release/split_gui${{ matrix.suffix }} ./split-gui${{ matrix.suffix }}
          ${{ matrix.comp_er }} ${{ matrix.comp_args }} "${{ env.pkg_name }}-${{ matrix.target }}.${{ matrix.comp_type }}" split-gui${{ matrix.suffix }} ./split_gui/assets/
          ls
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.pkg_name }}-${{ matrix.target }}
          path: |
            ${{ env.pkg_name }}-${{ matrix.target }}.${{ matrix.comp_type }}
          retention-days: 1

  pre-release:
    needs: build
    name: "Tag Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set package name
        id: set_name
        run: echo "pkg_name=split_gui" >> $GITHUB_ENV
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.pkg_name }}-x86_64-apple-darwin
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.pkg_name }}-x86_64-pc-windows-msvc
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "split-gui"
          prerelease: true
          title: "Split GUI Build"
          files: |
            ${{ env.pkg_name }}-x86_64-apple-darwin.tar.gz
            ${{ env.pkg_name }}-x86_64-pc-windows-msvc.zip
